//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerApplication
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Task
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public bool IsComplete { get; set; }

        public virtual Category Category { get; set; }
        public virtual Priority Priority { get; set; }
    }
}
